# This handles creation of images

steps:
  - id: "build django image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/django-app", "-f", "Dockerfile_app", "." ] # Specify Django Dockerfile
  - id: "push django image"
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/${PROJECT_ID}/django-app" ]

  - id: "build celery image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${_PROJECT_ID}/celery-worker", "-f", "Dockerfile_worker", "."]  # Specify Celery Dockerfile
  - id: "push celery image"
    name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/${PROJECT_ID}/celery-worker" ]

  - id: "apply migrations to django"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/${_PROJECT_ID}/django-app",  # Replace with built image tag
        "-s",
        "${_PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "-e",
        "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "collect static for django app"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
       [
         "-i",
         "gcr.io/${_PROJECT_ID}/celery-worker",
         "-s",
         "${_PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
         "-e",
         "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
         "--",
         "python",
         "manage.py",
         "collectstatic",
         "--verbosity",
         "2",
         "--no-input",
       ]

substitutions:
  _INSTANCE_NAME: celery-instance
  _PROJECT_ID: sensity-demo-app
  _REGION: us-central1
  _SECRET_SETTINGS_NAME: django_settings

images:
  - "gcr.io/${PROJECT_ID}/django-app"  # Django app image
  - "gcr.io/${PROJECT_ID}/celery-worker"  # Celery worker image
# [END cloudrun_django_cloudmigrate]
