apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flower-service
  namespace: '371205619153'
  selfLink: /apis/serving.knative.dev/v1/namespaces/371205619153/services/flower-service
  uid: 599df520-6a75-4626-b3d5-200178a4cb86
  resourceVersion: AAYXPIjKiQ4
  generation: 3
  creationTimestamp: '2024-04-29T13:45:45.305721Z'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: hashaam.hassan.work@gmail.com
    serving.knative.dev/lastModifier: hashaam.hassan.work@gmail.com
    run.googleapis.com/client-version: 473.0.0
    run.googleapis.com/operation-id: 4fbba474-ed5a-4988-ac66-5ae571ac84f7
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: yutayrimmd
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 473.0.0
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/vpc-access-connector: my-vpc-connector
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 371205619153-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/sensity-demo-app/flower-service
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
